id: P010414
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-19 20:48:30.162818
source_metadata:
  id: bdr:W1CZ1121
  title: ལུང་སྟོན་པ་ཀ་ལ་པའི་མདོ
  author: ''
  volumes:
    b74263ccf8ed49c686cd8654eab6e0d3:
      image_group_id: I1CZ1362
      title: ''
      volume_number: 1
      total_pages: 56
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
